//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChilLaxBackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ChilLaxEntities : DbContext
    {
        public ChilLaxEntities()
            : base("name=ChilLaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CustomerService> CustomerService { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FocusDetail> FocusDetail { get; set; }
        public virtual DbSet<FocusSlide> FocusSlide { get; set; }
        public virtual DbSet<HomeVideo> HomeVideo { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberCredential> MemberCredential { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<PointHistory> PointHistory { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductOrder> ProductOrder { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetail { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<TarotCard> TarotCard { get; set; }
        public virtual DbSet<TarotOrder> TarotOrder { get; set; }
    
        public virtual int sp_generate_order(Nullable<int> data_row)
        {
            var data_rowParameter = data_row.HasValue ?
                new ObjectParameter("data_row", data_row) :
                new ObjectParameter("data_row", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_generate_order", data_rowParameter);
        }
    
        public virtual int sp_generate_purchase(Nullable<int> data_row)
        {
            var data_rowParameter = data_row.HasValue ?
                new ObjectParameter("data_row", data_row) :
                new ObjectParameter("data_row", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_generate_purchase", data_rowParameter);
        }
    
        public virtual ObjectResult<sp_get_announcement_by_date_Result> sp_get_announcement_by_date(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_announcement_by_date_Result>("sp_get_announcement_by_date", startParameter, endParameter);
        }
    
        public virtual ObjectResult<Announcement> GetFunctionAnmt(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Announcement>("GetFunctionAnmt", startParameter, endParameter);
        }
    
        public virtual ObjectResult<Announcement> GetFunctionAnmt(Nullable<System.DateTime> start, Nullable<System.DateTime> end, MergeOption mergeOption)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Announcement>("GetFunctionAnmt", mergeOption, startParameter, endParameter);
        }
    }
}
