//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChilLaxBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_id { get; set; }
        public bool emp_permission { get; set; }
        public string emp_name { get; set; }
        public string emp_account { get; set; }
        public string emp_password { get; set; }
        public Nullable<bool> available { get; set; }
    }
}
